from pydantic import BaseModel, Field
from typing import List, Optional, Dict
from datetime import datetime

class AnalysisSource(BaseModel):
    timestamp: datetime = Field(default_factory=datetime.now)
    source_name: str
    
class CompanyOverview(BaseModel):
    symbol: str
    name: str
    sector: Optional[str]
    description: Optional[str]
    source: AnalysisSource

class MarketInfo(BaseModel):
    current_price: float
    previous_close: float
    volume: int
    day_high: float
    day_low: float
    source: AnalysisSource

class FundamentalAnalysis(BaseModel):
    market_cap: Optional[int]
    pe_ratio: Optional[float]
    eps: Optional[float]
    dividend_yield: Optional[float]
    profit_margin: Optional[float]
    revenue_growth: Optional[float]
    source: AnalysisSource

class TechnicalAnalysis(BaseModel):
    sma_50: Optional[float]
    sma_200: Optional[float]
    rsi_14: Optional[float]
    macd: Optional[float]
    macd_signal: Optional[float]
    price_trend: str = Field(..., description="Bullish, Bearish, or Neutral based on SMAs")
    volume_trend: str = Field(..., description="Increasing, Decreasing, or Stable")
    source: AnalysisSource

class RiskAnalysis(BaseModel):
    beta: Optional[float] = Field(None, description="Measure of volatility relative to market")
    volatility_30d: Optional[float] = Field(None, description="30-day historical volatility")
    fifty_two_week_high: Optional[float]
    fifty_two_week_low: Optional[float]
    risk_indicators: List[str] = Field(default_factory=list, description="e.g., 'High Beta', 'Close to 52w Low'")
    source: AnalysisSource

class NewsItem(BaseModel):
    headline: str
    url: str
    publisher: str
    published_at: str

class PeerComparison(BaseModel):
    peer_symbol: str
    pe_ratio: Optional[float]
    market_cap: Optional[int]

class StockAnalysisResponse(BaseModel):
    """
    The massive, unified response model for the Stock Analysis Engine.
    Enforces strict typing and sources for all data points.
    """
    symbol: str
    generated_at: datetime = Field(default_factory=datetime.now)
    
    overview: CompanyOverview
    market_info: MarketInfo
    fundamentals: FundamentalAnalysis
    technicals: TechnicalAnalysis
    risk_analysis: RiskAnalysis
    
    historical_prices: List[Dict[str, float]] = Field(default_factory=list, description="List of dicts with 'date' and 'close'")
    peers: List[PeerComparison] = Field(default_factory=list)
    recent_news: List[NewsItem] = Field(default_factory=list)
    
    ai_explanation: str = Field(
        ..., 
        description="Educational explanation generated by the LLM. MUST NOT contain financial advice or guarantees."
    )
